"""add title episode mediafile schema

Revision ID: 2b6a819e2a3d
Revises: 7e01018a8f60
Create Date: 2026-08-01 16:01:24.026533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2b6a819e2a3d'
down_revision: Union[str, None] = '7e01018a8f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chp_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('FILM', 'SERIAL', 'MULTFILM', 'ANIME', 'DRAMA', name='contenttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chp_titles_content_type'), 'chp_titles', ['content_type'], unique=False)
    op.create_index(op.f('ix_chp_titles_is_active'), 'chp_titles', ['is_active'], unique=False)
    op.create_index(op.f('ix_chp_titles_name'), 'chp_titles', ['name'], unique=False)
    op.create_index(op.f('ix_chp_titles_tmdb_id'), 'chp_titles', ['tmdb_id'], unique=False)
    op.create_table('chp_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['chp_titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id', 'season', 'number', name='uq_episode_per_title')
    )
    op.create_index(op.f('ix_chp_episodes_title_id'), 'chp_episodes', ['title_id'], unique=False)
    op.create_table('chp_media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('language', sa.Enum('UZ_DUB', 'UZ_SUB', 'RU', 'EN', 'ORIGINAL', name='audiolanguage'), nullable=False),
    sa.Column('quality', sa.Enum('SD_480', 'HD_720', 'FHD_1080', 'UHD_4K', name='videoquality'), nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['chp_episodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('episode_id', 'language', 'quality', name='uq_file_per_lang_quality')
    )
    op.create_index(op.f('ix_chp_media_files_episode_id'), 'chp_media_files', ['episode_id'], unique=False)
    op.create_index(op.f('ix_chp_media_files_language'), 'chp_media_files', ['language'], unique=False)
    sa.Enum('UZ', 'RU', 'EN', name='uilanguage').create(op.get_bind(), checkfirst=True)
    op.add_column('chp_users', sa.Column('language', sa.Enum('UZ', 'RU', 'EN', name='uilanguage'), nullable=False, server_default='UZ'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chp_users', 'language')
    sa.Enum('UZ', 'RU', 'EN', name='uilanguage').drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_chp_media_files_language'), table_name='chp_media_files')
    op.drop_index(op.f('ix_chp_media_files_episode_id'), table_name='chp_media_files')
    op.drop_table('chp_media_files')
    op.drop_index(op.f('ix_chp_episodes_title_id'), table_name='chp_episodes')
    op.drop_table('chp_episodes')
    op.drop_index(op.f('ix_chp_titles_tmdb_id'), table_name='chp_titles')
    op.drop_index(op.f('ix_chp_titles_name'), table_name='chp_titles')
    op.drop_index(op.f('ix_chp_titles_is_active'), table_name='chp_titles')
    op.drop_index(op.f('ix_chp_titles_content_type'), table_name='chp_titles')
    op.drop_table('chp_titles')
    # ### end Alembic commands ###
