"""add favorites

Revision ID: 68eba9169142
Revises: cfa148caa42b
Create Date: 2026-08-03 11:18:38.124509
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68eba9169142'
down_revision: Union[str, None] = 'cfa148caa42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chp_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['chp_titles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chp_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'title_id', name='uq_favorite_per_user')
    )
    op.create_index(op.f('ix_chp_favorites_title_id'), 'chp_favorites', ['title_id'], unique=False)
    op.create_index(op.f('ix_chp_favorites_user_id'), 'chp_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chp_favorites_user_id'), table_name='chp_favorites')
    op.drop_index(op.f('ix_chp_favorites_title_id'), table_name='chp_favorites')
    op.drop_table('chp_favorites')
    # ### end Alembic commands ###
