"""add user.language_selected

Revision ID: 6b7ec8ebd218
Revises: 68eba9169142
Create Date: 2026-08-03 18:43:46.883790
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6b7ec8ebd218'
down_revision: Union[str, None] = '68eba9169142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('chp_users', sa.Column('language_selected', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # Everyone who already exists is an existing user by definition, and the
    # Mini App must not interrupt them with a picker for a setting they've
    # been living with. The server_default of false is for rows created from
    # here on — those are the genuinely new users who should be asked.
    op.execute("UPDATE chp_users SET language_selected = true")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chp_users', 'language_selected')
    # ### end Alembic commands ###
