"""add watch history

Revision ID: 78dab4021c4a
Revises: 9eed61bb0705
Create Date: 2026-08-02 15:09:33.629307
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '78dab4021c4a'
down_revision: Union[str, None] = '9eed61bb0705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chp_watch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('watch_count', sa.Integer(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['chp_episodes.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['chp_titles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chp_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'episode_id', name='uq_watch_per_user_episode')
    )
    op.create_index(op.f('ix_chp_watch_history_episode_id'), 'chp_watch_history', ['episode_id'], unique=False)
    op.create_index(op.f('ix_chp_watch_history_last_watched_at'), 'chp_watch_history', ['last_watched_at'], unique=False)
    op.create_index(op.f('ix_chp_watch_history_title_id'), 'chp_watch_history', ['title_id'], unique=False)
    op.create_index(op.f('ix_chp_watch_history_user_id'), 'chp_watch_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chp_watch_history_user_id'), table_name='chp_watch_history')
    op.drop_index(op.f('ix_chp_watch_history_title_id'), table_name='chp_watch_history')
    op.drop_index(op.f('ix_chp_watch_history_last_watched_at'), table_name='chp_watch_history')
    op.drop_index(op.f('ix_chp_watch_history_episode_id'), table_name='chp_watch_history')
    op.drop_table('chp_watch_history')
    # ### end Alembic commands ###
