"""baseline: all CinemaHub Pro tables

Revision ID: 7e01018a8f60
Revises: 
Create Date: 2026-07-31 19:04:24.741143
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7e01018a8f60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chp_admin_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=False),
    sa.Column('holder_name', sa.String(length=128), nullable=False),
    sa.Column('bank_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chp_movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('file_id', sa.String(length=255), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=False),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chp_movies_title'), 'chp_movies', ['title'], unique=False)
    op.create_index(op.f('ix_chp_movies_tmdb_id'), 'chp_movies', ['tmdb_id'], unique=True)
    op.create_table('chp_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'MODERATOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ai_requests_today', sa.Integer(), nullable=False),
    sa.Column('ai_limit_reset_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('monthly_orders_count', sa.Integer(), nullable=False),
    sa.Column('monthly_limit_reset_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['chp_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chp_users_referral_code'), 'chp_users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_chp_users_telegram_id'), 'chp_users', ['telegram_id'], unique=True)
    op.create_table('chp_balance_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tx_type', sa.Enum('TOPUP', 'DEDUCTION', 'REFUND', 'ADMIN_ADJUSTMENT', 'PROMO_CREDIT', name='balancetxtype'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['chp_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chp_balance_history_user_id'), 'chp_balance_history', ['user_id'], unique=False)
    op.create_table('chp_payment_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_card_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('TOPUP', 'SUBSCRIPTION', name='paymentpurpose'), nullable=False),
    sa.Column('subscription_plan', sa.Enum('FREE', 'PREMIUM', name='subscriptionplan'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('receipt_photo_file_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='paymentstatus'), nullable=False),
    sa.Column('admin_notes', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_card_id'], ['chp_admin_cards.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['chp_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chp_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chp_payment_receipts_status'), 'chp_payment_receipts', ['status'], unique=False)
    op.create_index(op.f('ix_chp_payment_receipts_user_id'), 'chp_payment_receipts', ['user_id'], unique=False)
    op.create_table('chp_promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('campaign_name', sa.String(length=128), nullable=True),
    sa.Column('discount_type', sa.Enum('FIXED_AMOUNT_BALANCE', 'PREMIUM_DAYS', 'PERCENTAGE_DISCOUNT', name='promodiscounttype'), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['chp_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chp_promo_codes_code'), 'chp_promo_codes', ['code'], unique=True)
    op.create_table('chp_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PREMIUM', name='subscriptionplan'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['chp_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chp_subscriptions_user_id'), 'chp_subscriptions', ['user_id'], unique=False)
    op.create_table('chp_promo_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['chp_promo_codes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['chp_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promo_code_id', 'user_id', name='uq_promo_usage_per_user')
    )
    op.create_index(op.f('ix_chp_promo_usages_promo_code_id'), 'chp_promo_usages', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_chp_promo_usages_user_id'), 'chp_promo_usages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chp_promo_usages_user_id'), table_name='chp_promo_usages')
    op.drop_index(op.f('ix_chp_promo_usages_promo_code_id'), table_name='chp_promo_usages')
    op.drop_table('chp_promo_usages')
    op.drop_index(op.f('ix_chp_subscriptions_user_id'), table_name='chp_subscriptions')
    op.drop_table('chp_subscriptions')
    op.drop_index(op.f('ix_chp_promo_codes_code'), table_name='chp_promo_codes')
    op.drop_table('chp_promo_codes')
    op.drop_index(op.f('ix_chp_payment_receipts_user_id'), table_name='chp_payment_receipts')
    op.drop_index(op.f('ix_chp_payment_receipts_status'), table_name='chp_payment_receipts')
    op.drop_table('chp_payment_receipts')
    op.drop_index(op.f('ix_chp_balance_history_user_id'), table_name='chp_balance_history')
    op.drop_table('chp_balance_history')
    op.drop_index(op.f('ix_chp_users_telegram_id'), table_name='chp_users')
    op.drop_index(op.f('ix_chp_users_referral_code'), table_name='chp_users')
    op.drop_table('chp_users')
    op.drop_index(op.f('ix_chp_movies_tmdb_id'), table_name='chp_movies')
    op.drop_index(op.f('ix_chp_movies_title'), table_name='chp_movies')
    op.drop_table('chp_movies')
    op.drop_table('chp_admin_cards')
    # ### end Alembic commands ###
