"""add collections

Revision ID: cfa148caa42b
Revises: 78dab4021c4a
Create Date: 2026-08-03 10:54:48.818945
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cfa148caa42b'
down_revision: Union[str, None] = '78dab4021c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chp_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chp_collections_is_active'), 'chp_collections', ['is_active'], unique=False)
    op.create_index(op.f('ix_chp_collections_name'), 'chp_collections', ['name'], unique=True)
    op.create_index(op.f('ix_chp_collections_slug'), 'chp_collections', ['slug'], unique=True)
    op.create_table('chp_title_collections',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['chp_collections.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['chp_titles.id'], ),
    sa.PrimaryKeyConstraint('title_id', 'collection_id')
    )
    op.create_index(op.f('ix_chp_title_collections_collection_id'), 'chp_title_collections', ['collection_id'], unique=False)
    op.create_index(op.f('ix_chp_title_collections_title_id'), 'chp_title_collections', ['title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chp_title_collections_title_id'), table_name='chp_title_collections')
    op.drop_index(op.f('ix_chp_title_collections_collection_id'), table_name='chp_title_collections')
    op.drop_table('chp_title_collections')
    op.drop_index(op.f('ix_chp_collections_slug'), table_name='chp_collections')
    op.drop_index(op.f('ix_chp_collections_name'), table_name='chp_collections')
    op.drop_index(op.f('ix_chp_collections_is_active'), table_name='chp_collections')
    op.drop_table('chp_collections')
    # ### end Alembic commands ###
